GET https://habitica.com/api/v3/tagsX-Api-User: {{apiUser}}X-Api-Key: {{apiToken}}Content-Type: application/json>> {{responseFolder}}/r.json###POST https://habitica.com/api/v3/tagsX-Api-User: {{apiUser}}X-Api-Key: {{apiToken}}Content-Type: application/json{  "name": "free"}>> {{responseFolder}}/r.json###DELETE https://habitica.com/api/v3/tags/ece54769-cc97-48a7-a240-3beb924a5158X-Api-User: {{apiUser}}X-Api-Key: {{apiToken}}Content-Type: application/json>> {{responseFolder}}/r.json